version: "3.9"

services:
  redis-db:
    extends:
      file: ./services/redis.yml
      service: redis-db
    networks:
      - dokploy-network

  db-init:
    extends:
      file: ./services/db.yml
      service: db-init
    networks:
      - dokploy-network

  db:
    depends_on:
      db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/db.yml
      service: db
    networks:
      - dokploy-network

  backend:
    depends_on:
      - db
      - redis-db
    extends:
      file: ./services/backend.yml
      service: backend
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        RELEASE_VERSION: 7.0.2
    links:
      - db:database
    environment:
      ETHEREUM_JSONRPC_HTTP_URL: http://109.71.253.219:8545/
      ETHEREUM_JSONRPC_TRACE_URL: http://109.71.253.219:8545/
      ETHEREUM_JSONRPC_WS_URL: ws://109.71.253.219:8545/
      CHAIN_ID: "6666"
    networks:
      - dokploy-network

  nft_media_handler:
    depends_on:
      - backend
    extends:
      file: ./services/nft_media_handler.yml
      service: nft_media_handler
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        RELEASE_VERSION: 7.0.2
    networks:
      - dokploy-network

  visualizer:
    extends:
      file: ./services/visualizer.yml
      service: visualizer
    networks:
      - dokploy-network

  sig-provider:
    extends:
      file: ./services/sig-provider.yml
      service: sig-provider
    networks:
      - dokploy-network

  frontend:
    depends_on:
      - backend
    extends:
      file: ./services/frontend.yml
      service: frontend
    networks:
      - dokploy-network

  stats-db-init:
    extends:
      file: ./services/stats.yml
      service: stats-db-init
    networks:
      - dokploy-network

  stats-db:
    depends_on:
      stats-db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/stats.yml
      service: stats-db
    networks:
      - dokploy-network

  stats:
    depends_on:
      - stats-db
      - backend
    extends:
      file: ./services/stats.yml
      service: stats
    networks:
      - dokploy-network

  user-ops-indexer:
    depends_on:
      - db
      - backend
    extends:
      file: ./services/user-ops-indexer.yml
      service: user-ops-indexer
    networks:
      - dokploy-network

  proxy:
    depends_on:
      - backend
      - frontend
      - stats
    extends:
      file: ./services/nginx.dokply.yml
      service: proxy
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
